### PR TITLE
Add GNOME HIG style icon

### LINKED ISSUE #2: Icon
Inspiration: Boxhagener Platz, in Berlin

https://www.openstreetmap.org/#map=19/52.51078/13.45957

image

https://www.google.com/maps/place/Boxhagener+Platz/@52.5108668,13.4595849,240m/data=!3m2!1e3!4b1

image

Here's a highly abstract version with colors of the components of the "square" rounded to GNOME colors, attempting to adhere to the GNOME Icon design guidelines:

image
 
Source SVG: 
org.boxi.Boxi Source

Icon SVG:
org boxi Boxi

Devel icon SVG:
org boxi Boxi Devel

Symbolic icon SVG:
org boxi Boxi-symbolic

### PR DESCRIPTION
**Pull request by garrett**
Closes #2.

Here's what it looks like in context:

image

### CODE REVIEW

**Comment by garrett** [comment]
This PR doesn't add the symbolic or dev versions, however.

Symbolic:

org boxi Boxi-symbolic

Dev:

org boxi Boxi Devel

**Review by allisonkarlitskaya — CHANGES_REQUESTED** [review]
Thanks for this!  It looks great.

Can you also add the symbolic icon in the correct place?

**Comment by garrett** [comment]
> Can you also add the symbolic icon in the correct place?

I'm not sure where the correct place is.

Edit: Aha. I think I know. I'll try now.

**Comment by garrett** [comment]
OK, added.

...Although the icons use z.y, instead of z.y.X naming. But this PR doesn't address that.

(That is... `dev.boxi` instead of something like `dev.boxi.Boxi`.)

**Review by allisonkarlitskaya — APPROVED** [review]

**Pull request merged**
